// Teste do endpoint dos usuários
@baseURL = http://localhost:4000/api/produto

###
POST {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIn0sImlhdCI6MTcxNTgxOTM0OSwiZXhwIjoxNzE1OTA1NzQ5fQ.jbXZ05iB5G-SHneOUJME6LHXNdq_aL4JYGY37BE7LX0

{
    "nome": "Celular",
    "categoria": "pequeno",
    "reutilizavel": true
}

###
// GET - Lista todos os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIn0sImlhdCI6MTcxNTgxOTM0OSwiZXhwIjoxNzE1OTA1NzQ5fQ.jbXZ05iB5G-SHneOUJME6LHXNdq_aL4JYGY37BE7LX0

###
PUT {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIn0sImlhdCI6MTcxNTgxOTM0OSwiZXhwIjoxNzE1OTA1NzQ5fQ.jbXZ05iB5G-SHneOUJME6LHXNdq_aL4JYGY37BE7LX0

{
    "_id": "664554a2abe512b6c9ade547",
    "nome": "Celular",
    "categoria": "pequeno",
    "reutilizavel": true
  }

###
DELETE {{baseURL}}/66455a10db1af4c8c86653a7
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIn0sImlhdCI6MTcxNTgxOTM0OSwiZXhwIjoxNzE1OTA1NzQ5fQ.jbXZ05iB5G-SHneOUJME6LHXNdq_aL4JYGY37BE7LX0