// Teste do endpoint dos usuários
@baseURL = http://localhost:4000/api/usuario

###
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Mateus",
    "email": "sandman2871@gmail.com",
    "senha": "Mateus123#",
    "tipo": "Admin"
}

###
// GET - Lista todos os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0MTYxYjc5YTk0ZTYxZTRlYWRjNmQ2In0sImlhdCI6MTcxNTU2MTA2OCwiZXhwIjoxNzE1NjQ3NDY4fQ.LsmGiyFKhhBV3z9eomvLgfnt9r8VltAw_dNyG7bXTRk

###
// POST - Efetua o login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "sandman2871@gmail.com",
    "senha": "Mateus123#"
}