// Teste do endpoint dos usuários
@baseURL = http://localhost:4000/api/usuario

###
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Mateus",
    "email": "mateus@gmail.com",
    "senha": "Mateus123#",
    "tipo": "Cliente",
    "pontos": 300
}

###
// GET - Lista todos os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIiwidGlwbyI6IkFkbWluIn0sImlhdCI6MTcxNzI2Mzg1MywiZXhwIjoxNzE3MzUwMjUzfQ.uSqEAsaGIV14dmLCbx6oUQRtX37qinyqSB1VaS60JkQ

###
// POST - Efetua o login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "sandman2871@gmail.com",
    "senha": "Mateus123#"
}

###
GET {{baseURL}}/id/66455346790bab4c8d53b4aa
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIn0sImlhdCI6MTcxNjc1NTEyNywiZXhwIjoxNzE2ODQxNTI3fQ.mm6E1ESpyU2nMgi_kgn29FwiT8f89f8FyN694hJU2Z8


###
GET {{baseURL}}/pontos
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0NTUzNDY3OTBiYWI0YzhkNTNiNGFhIiwidGlwbyI6IkFkbWluIn0sImlhdCI6MTcxNzQ1MTcxMCwiZXhwIjoxNzE3NTM4MTEwfQ.qDScLBYBWlJXXLithiGtBCnSldCkstt1LWBpsg5GTaw
